# Generated by Django 3.0.3 on 2020-02-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20200213_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registered_date',
        ),
    ]
