# Generated by Django 3.0.3 on 2020-02-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
